export const vulnerabilities = [
  {
    value: 'RISK_OF_SUICIDE_OR_SELF_HARM',
    text: 'At risk of suicide or self-harm',
    detailsLabel: 'Give details',
    category: 'Suicide or self-harm',
    categoryHint:
      'Consider if a history of a self-harm, sentense type, separation from family, or any other factor, could trigger a suicide or self-harm attempt',
  },
  {
    value: 'DRUG_OR_ALCOHOL_USE',
    text: 'Drug and alcohol abuse',
    detailsLabel: 'Give details',
    category: 'Health and wellbeing',
    categoryHint: '',
  },
  {
    value: 'MENTAL_HEALTH_CONCERNS',
    text: 'Mental health concerns',
    detailsLabel: 'Give details',
    category: 'Health and wellbeing',
    categoryHint: '',
  },
  {
    value: 'MEDICATION_TAKEN_INCLUDING_COMPLIANCE_WITH_MEDICATION',
    text: 'Medication taken, including compliance with medication',
    detailsLabel: 'Give details',
    category: 'Health and wellbeing',
    categoryHint: '',
  },
  {
    value: 'PHYSICAL_HEALTH_CONCERNS',
    text: 'Physical health concerns',
    detailsLabel: 'Give details',
    category: 'Health and wellbeing',
    categoryHint: '',
  },
  {
    value: 'LEARNING_DIFFICULTIES',
    text: 'Learning difficulties',
    detailsLabel: 'Give details',
    category: 'Health and wellbeing',
    categoryHint: '',
  },
  {
    value: 'PHYSICAL_DISABILITIES',
    text: 'Physical disabilities',
    detailsLabel: 'Give details',
    category: 'Health and wellbeing',
    categoryHint: '',
  },
  {
    value: 'DOMESTIC_ABUSE',
    text: 'Domestic abuse',
    detailsLabel: 'Give details',
    category: 'A risk to or from others',
    categoryHint: '',
  },
  {
    value: 'ADULT_OR_CHILD_SAFEGUARDING_CONCERNS',
    text: 'Adult or child safeguarding concerns',
    detailsLabel: 'Give details',
    category: 'A risk to or from others',
    categoryHint: '',
  },
  {
    value: 'BEING_AT_RISK_OF_SERIOUS_HARM_FROM_OTHERS',
    text: 'Being at risk of serious harm from others',
    detailsLabel: 'Give details',
    category: 'A risk to or from others',
    categoryHint: '',
  },
  {
    value: 'BEING_BULLIED_BY_OTHERS',
    text: 'Being bullied by others',
    detailsLabel: 'Give details',
    category: 'A risk to or from others',
    categoryHint: '',
  },
  {
    value: 'BULLYING_OTHERS',
    text: 'Bullying others',
    detailsLabel: 'Give details',
    category: 'A risk to or from others',
    categoryHint: '',
  },
  {
    value: 'RELATIONSHIP_BREAKDOWN',
    text: 'Relationship breakdown',
    detailsLabel: 'Give details',
    category: 'Relationships, family, and community',
    categoryHint: '',
  },
  {
    value: 'BEREAVEMENT_ISSUES',
    text: 'Bereavement issues',
    detailsLabel: 'Give details',
    category: 'Relationships, family, and community',
    categoryHint: '',
  },
  {
    value: 'CULTURAL_OR_LANGUAGE_DIFFERENCES',
    text: 'Cultural or language differences',
    detailsLabel: 'Give details',
    category: 'Relationships, family, and community',
    categoryHint: '',
  },
  {
    value: 'NONE_OR_NOT_KNOWN',
    text: 'No concerns or do not know',
    behaviour: 'exclusive',
    category: 'Or no concerns or knowledge of vulnerabilities',
    categoryHint: '',
    items: [
      {
        value: 'NONE',
        text: 'No concerns about vulnerabilities or needs',
      },
      {
        value: 'NOT_KNOWN',
        text: 'Do not know about vulnerabilities or needs',
      },
    ],
  },
]
