version: '3.1'
services:

  redis:
    image: 'cimg/redis:7.4.2'
    networks:
      - hmpps_int
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  wiremock:
    image: rodolpheche/wiremock
    networks:
    - hmpps_int
    container_name: wiremock
    restart: always
    ports:
      - "9091:8080"

  mock-flipt-api:
    image: wiremock/wiremock
    networks:
      - hmpps
    container_name: mock-flipt-api
    ports:
      - "7070:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/ping" ]
    command: --verbose --local-response-templating
    volumes:
      - ./mock-flipt-api:/home/wiremock

networks:
  hmpps_int:
