/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type { ActiveRecommendation } from './models/ActiveRecommendation';
export type { AdditionalLicenceConditionOption } from './models/AdditionalLicenceConditionOption';
export type { AdditionalLicenceConditions } from './models/AdditionalLicenceConditions';
export type { AlternativesToRecallTried } from './models/AlternativesToRecallTried';
export type { CaseDocument } from './models/CaseDocument';
export type { CaseDocumentType } from './models/CaseDocumentType';
export type { CaseSummaryOverviewResponse } from './models/CaseSummaryOverviewResponse';
export type { CircumstancesIncreaseRisk } from './models/CircumstancesIncreaseRisk';
export type { ContactGroupResponse } from './models/ContactGroupResponse';
export type { ContactHistoryResponse } from './models/ContactHistoryResponse';
export type { ContactSummaryResponse } from './models/ContactSummaryResponse';
export type { ContingencyPlan } from './models/ContingencyPlan';
export type { ConvictionResponse } from './models/ConvictionResponse';
export type { CreateRecommendationRequest } from './models/CreateRecommendationRequest';
export type { CurrentAddress } from './models/CurrentAddress';
export { CustodyStatus } from './models/CustodyStatus';
export type { FactorsToReduceRisk } from './models/FactorsToReduceRisk';
export type { HistoricalScore } from './models/HistoricalScore';
export type { JsonNode } from './models/JsonNode';
export type { LastRecall } from './models/LastRecall';
export type { LastRelease } from './models/LastRelease';
export type { LicenceCondition } from './models/LicenceCondition';
export type { LicenceConditionsBreached } from './models/LicenceConditionsBreached';
export type { LicenceConditionsResponse } from './models/LicenceConditionsResponse';
export type { LicenceConditionTypeMainCat } from './models/LicenceConditionTypeMainCat';
export type { LicenceConditionTypeSubCat } from './models/LicenceConditionTypeSubCat';
export type { Mappa } from './models/Mappa';
export type { NatureOfRisk } from './models/NatureOfRisk';
export type { OasysHeading } from './models/OasysHeading';
export type { Offence } from './models/Offence';
export type { OffenderManager } from './models/OffenderManager';
export type { OGRS } from './models/OGRS';
export type { OSPC } from './models/OSPC';
export type { OSPI } from './models/OSPI';
export type { OverviewConvictionResponse } from './models/OverviewConvictionResponse';
export type { PartAResponse } from './models/PartAResponse';
export type { PersonDetails } from './models/PersonDetails';
export type { PersonDetailsResponse } from './models/PersonDetailsResponse';
export type { PersonOnProbation } from './models/PersonOnProbation';
export type { PredictorScores } from './models/PredictorScores';
export type { ProbationTeam } from './models/ProbationTeam';
export type { Reason } from './models/Reason';
export type { RecallType } from './models/RecallType';
export { RecallTypeSelectedValue } from './models/RecallTypeSelectedValue';
export { RecommendationResponse } from './models/RecommendationResponse';
export type { ReleaseSummaryResponse } from './models/ReleaseSummaryResponse';
export type { Risk } from './models/Risk';
export type { RiskOfSeriousHarm } from './models/RiskOfSeriousHarm';
export type { RiskPersonalDetails } from './models/RiskPersonalDetails';
export type { RiskResponse } from './models/RiskResponse';
export type { RSR } from './models/RSR';
export type { Scores } from './models/Scores';
export type { SearchByCrnResponse } from './models/SearchByCrnResponse';
export type { SelectedWithDetails } from './models/SelectedWithDetails';
export type { StandardLicenceConditions } from './models/StandardLicenceConditions';
export type { TextValueOption } from './models/TextValueOption';
export type { UnderIntegratedOffenderManagement } from './models/UnderIntegratedOffenderManagement';
export type { UserAccessResponse } from './models/UserAccessResponse';
export type { ValueWithDetails } from './models/ValueWithDetails';
export { VictimsInContactScheme } from './models/VictimsInContactScheme';
export type { WhenRiskHighest } from './models/WhenRiskHighest';
export type { WhoIsAtRisk } from './models/WhoIsAtRisk';
