enum StageEnum {
  STARTED = 'STARTED',
  OFFENDER_BOOKED = 'OFFENDER_BOOKED',
  SENTENCE_BOOKED = 'SENTENCE_BOOKED',
  OFFENCE_BOOKED = 'OFFENCE_BOOKED',
  RELEASE_BOOKED = 'RELEASE_BOOKED',
  RECALL_BOOKED = 'RECALL_BOOKED',
  POSTING_RECALL_DATA = 'POSTING_RECALL_DATA',
  UPLOADING_DOCUMENTS = 'UPLOADING_DOCUMENTS',
  BOOKING_MINUTE = 'BOOKING_MINUTE',
  MINUTE_BOOKED = 'MINUTE_BOOKED',
}

export default StageEnum
