export enum StageEnum {
  STARTED = 'STARTED',
  OFFENDER_BOOKED = 'OFFENDER_BOOKED',
  SENTENCE_BOOKED = 'SENTENCE_BOOKED',
  OFFENCE_BOOKED = 'OFFENCE_BOOKED',
  RELEASE_BOOKED = 'RELEASE_BOOKED',
  RECALL_BOOKED = 'RECALL_BOOKED',
}
