# Per environment values which override defaults in make-recall-decision-ui/values.yaml

generic-service:
  ingress:
    host: consider-a-recall.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    INGRESS_URL: "https://consider-a-recall.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    MAKE_RECALL_DECISION_API_URL: "http://make-recall-decision-api.make-recall-decision-prod.svc.cluster.local"
    MANAGE_USERS_API_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"
    MAKE_RECALL_DECISIONS_AND_DELIUS_API_URL: "https://make-recall-decisions-and-delius.hmpps.service.justice.gov.uk"
    COMPONENT_API_URL: "https://probation-frontend-components.hmpps.service.justice.gov.uk"
    SENTRY_ENVIRONMENT: "PROD"
    ENVIRONMENT: "prod"
    FLIPT_SERVER_URL: "https://feature-toggles.hmpps.service.justice.gov.uk/"
    FLIPT_NAMESPACE: "consider-a-recall"
    FEATURE_FLAG_QUERY_PARAMETERS_ENABLED: false
    FEATURE_FLAGFTR56ENABLED: "2026-03-30T23:00Z" # Midnight BST on 31st March 2026

  allowlist:
    north_shields_user: 194.33.192.1/24
    kettering_user: 194.33.196.4/24
    ark-dom1-farnborough: 194.33.192.0/24
    groups:
      - internal
      - prisons # do not remove, the prisons group also covers probation
      - probation

generic-prometheus-alerts:
  alertSeverity: make-recall-decision-prod
